version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - mvn -version

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Building the project and running tests...
      - mvn clean package

artifacts:
  files:
    - target/*-runner.jar

cache:
  paths:
    - /root/.m2/repository/**/*
